In [ ]:
import tensorflow  as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/heart.csv")
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [ ]:
data.isnull().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [ ]:
x=data.iloc[:,:13].values
y=data['target'].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
ssc=StandardScaler()
x_train=ssc.fit_transform(x_train)
x_test=ssc.transform(x_test)

In [ ]:
classifier=Sequential()
classifier.add(Dense(activation='relu',input_dim=13,units=8,kernel_initializer='uniform'))
classifier.add(Dense(activation='relu' , units=14, kernel_initializer='uniform'))
classifier.add(Dense(activation='sigmoid', units=1, kernel_initializer='uniform'))
classifier.compile(optimizer='adam' , loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
classifier.fit(x_train ,y_train ,batch_size=8 , epochs=100)

Epoch 1/100
27/27 [==============================] - 1s 2ms/step - loss: 0.6926 - accuracy: 0.5519
Epoch 2/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6887 - accuracy: 0.5566
Epoch 3/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6735 - accuracy: 0.6368
Epoch 4/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6344 - accuracy: 0.7972
Epoch 5/100
27/27 [==============================] - 0s 2ms/step - loss: 0.5705 - accuracy: 0.8349
Epoch 6/100
27/27 [==============================] - 0s 2ms/step - loss: 0.5006 - accuracy: 0.8396
Epoch 7/100
27/27 [==============================] - 0s 3ms/step - loss: 0.4426 - accuracy: 0.8491
Epoch 8/100
27/27 [==============================] - 0s 2ms/step - loss: 0.4003 - accuracy: 0.8632
Epoch 9/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3711 - accuracy: 0.8585
Epoch 10/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.8585
Epoch 11/100
27/27 [==============================] - 0s 3ms/step - loss: 0.3388 - accuracy: 0.8726
Epoch 12/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3291 - accuracy: 0.8774
Epoch 13/100
27/27 [==============================] - 0s 3ms/step - loss: 0.3235 - accuracy: 0.8679
Epoch 14/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3196 - accuracy: 0.8679
Epoch 15/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3171 - accuracy: 0.8679
Epoch 16/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3132 - accuracy: 0.8774
Epoch 17/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3115 - accuracy: 0.8726
Epoch 18/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3097 - accuracy: 0.8821
Epoch 19/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3073 - accuracy: 0.8821
Epoch 20/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3055 - accuracy: 0.8821
Epoch 21/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3052 - accuracy: 0.8821
Epoch 22/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3036 - accuracy: 0.8868
Epoch 23/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3031 - accuracy: 0.8868
Epoch 24/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3000 - accuracy: 0.8868
Epoch 25/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2994 - accuracy: 0.8868
Epoch 26/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2987 - accuracy: 0.8915
Epoch 27/100
27/27 [==============================] - 0s 3ms/step - loss: 0.2970 - accuracy: 0.8868
Epoch 28/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2968 - accuracy: 0.8868
Epoch 29/100
27/27 [==============================] - 0s 3ms/step - loss: 0.2954 - accuracy: 0.8962
Epoch 30/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2941 - accuracy: 0.8915
Epoch 31/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2926 - accuracy: 0.8868
Epoch 32/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2927 - accuracy: 0.9009
Epoch 33/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2918 - accuracy: 0.8962
Epoch 34/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2890 - accuracy: 0.8915
Epoch 35/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2878 - accuracy: 0.8868
Epoch 36/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2872 - accuracy: 0.8915
Epoch 37/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2861 - accuracy: 0.8962
Epoch 38/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2847 - accuracy: 0.8868
Epoch 39/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2830 - accuracy: 0.9009
Epoch 40/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2817 - accuracy: 0.8915
Epoch 41/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2817 - accuracy: 0.8915
Epoch 42/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2787 - accuracy: 0.8962
Epoch 43/100
27/27 [==============================] - 0s 3ms/step - loss: 0.2785 - accuracy: 0.8962
Epoch 44/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2771 - accuracy: 0.8962
Epoch 45/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2759 - accuracy: 0.9009
Epoch 46/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2753 - accuracy: 0.8962
Epoch 47/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2736 - accuracy: 0.9009
Epoch 48/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2723 - accuracy: 0.8962
Epoch 49/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2727 - accuracy: 0.9009
Epoch 50/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2714 - accuracy: 0.9009
Epoch 51/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2696 - accuracy: 0.9009
Epoch 52/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2694 - accuracy: 0.8962
Epoch 53/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2678 - accuracy: 0.9057
Epoch 54/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2682 - accuracy: 0.9057
Epoch 55/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2666 - accuracy: 0.9057
Epoch 56/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2661 - accuracy: 0.9104
Epoch 57/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2655 - accuracy: 0.9104
Epoch 58/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2647 - accuracy: 0.9104
Epoch 59/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2627 - accuracy: 0.9151
Epoch 60/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2617 - accuracy: 0.9151
Epoch 61/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2613 - accuracy: 0.9151
Epoch 62/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2605 - accuracy: 0.9151
Epoch 63/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2602 - accuracy: 0.9104
Epoch 64/100
27/27 [==============================] - 0s 3ms/step - loss: 0.2589 - accuracy: 0.9104
Epoch 65/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2576 - accuracy: 0.9151
Epoch 66/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2569 - accuracy: 0.9151
Epoch 67/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2566 - accuracy: 0.9151
Epoch 68/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2553 - accuracy: 0.9151
Epoch 69/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2546 - accuracy: 0.9151
Epoch 70/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2525 - accuracy: 0.9151
Epoch 71/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2516 - accuracy: 0.9151
Epoch 72/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2513 - accuracy: 0.9151
Epoch 73/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2504 - accuracy: 0.9151
Epoch 74/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2486 - accuracy: 0.9151
Epoch 75/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2488 - accuracy: 0.9104
Epoch 76/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2463 - accuracy: 0.9151
Epoch 77/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2457 - accuracy: 0.9151
Epoch 78/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2449 - accuracy: 0.9151
Epoch 79/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2434 - accuracy: 0.9151
Epoch 80/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2424 - accuracy: 0.9151
Epoch 81/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2415 - accuracy: 0.9104
Epoch 82/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2406 - accuracy: 0.9151
Epoch 83/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2396 - accuracy: 0.9198
Epoch 84/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2385 - accuracy: 0.9151
Epoch 85/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2360 - accuracy: 0.9245
Epoch 86/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2355 - accuracy: 0.9151
Epoch 87/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2344 - accuracy: 0.9151
Epoch 88/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2329 - accuracy: 0.9198
Epoch 89/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2314 - accuracy: 0.9198
Epoch 90/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2306 - accuracy: 0.9198
Epoch 91/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2287 - accuracy: 0.9245
Epoch 92/100
27/27 [==============================] - 0s 3ms/step - loss: 0.2281 - accuracy: 0.9198
Epoch 93/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2283 - accuracy: 0.9151
Epoch 94/100
27/27 [==============================] - 0s 3ms/step - loss: 0.2259 - accuracy: 0.9245
Epoch 95/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2238 - accuracy: 0.9245
Epoch 96/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2236 - accuracy: 0.9245
Epoch 97/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2211 - accuracy: 0.9245
Epoch 98/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2202 - accuracy: 0.9198
Epoch 99/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2196 - accuracy: 0.9245
Epoch 100/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2175 - accuracy: 0.9292

In [ ]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred > 0.5)

3/3 [==============================] - 0s 4ms/step

In [ ]:
y_pred

array([[False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

In [ ]:

a=int(input("age :"))
b=int(input("sex :"))
c=int(input("cp :"))
d=int(input("trestbps :"))
e=int(input("chol	:"))
f=int(input("fbs :"))
g=int(input("	restecg	:"))
h=int(input("thalach :"))
i=int(input("exang	:"))
j=int(input("oldpeak :"))
k=int(input("slope	 :"))
l=int(input("ca	:"))
m=int(input("thal	:"))
df=pd.DataFrame({"age":[a],
                 "sex":[b],
                 "cp":[c],
                 "trestbps":[d],
                 "chol":[e],
                 "fbs":[f],
                 "restecg":[g],
                 "thalach":[h],
                 "exang":[i],
                 "oldpeak":[j],
                 "slope":[k],
                 "ca":[l],
                 "thal":[m]})
df

age :57
sex :0
cp :0
trestbps :140
chol	:241
fbs :0
	restecg	:1
thalach :123
exang	:1
oldpeak :0
slope	 :1
ca	:0
thal	:3

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,57,0,0,140,241,0,1,123,1,0,1,0,3

In [ ]:
y_predict=classifier.predict(df)
y_predict
y_predict=(y_pred > 0.5)
if y_predict==[[1.]]:
  print("True")
else:
  print("False")

1/1 [==============================] - 0s 56ms/step

ValueError: ignored

In [ ]:
\145a=int(input("age :"))
b=int(input("sex :"))
c=int(input("cp :"))
d=int(input("trestbps :"))
e=int(input("chol	:"))
f=int(input("fbs :"))
g=int(input("	restecg	:"))
h=int(input("thalach :"))
i=int(input("exang	 :"))
j=int(input("oldpeak :"))
k=int(input("slope	 :"))
l=int(input("ca	:"))
m=int(input("thal	:"))
df1=pd.DataFrame({"age":[a],
                 "sex":[b],
                 "cp":[c],
                 "trestbps":[d],
                 "chol":[e],
                 "fbs":[f],
                 "restecg":[g],
                 "thalach":[h],
                 "exang":[i],
                 "oldpeak":[j],
                 "slope":[k],
                 "ca":[l],
                 "thal":[m]})
df1

In [ ]:
y_prediction=classifier.predict(df1)
y_prediction

# if y_prediction==[[1.]]:
#   print("True")
# else:
#   print("False")

In [ ]:
a=int(input("age :"))
b=int(input("sex :"))
c=int(input("cp :"))
d=int(input("trestbps :"))
e=int(input("chol	:"))
f=int(input("fbs :"))
g=int(input("	restecg	:"))
h=int(input("thalach :"))
i=int(input("exang	 :"))
j=int(input("oldpeak :"))
k=int(input("slope	 :"))
l=int(input("ca	:"))
m=int(input("thal	:"))
df2=pd.DataFrame({"age":[a],
                 "sex":[b],
                 "cp":[c],
                 "trestbps":[d],
                 "chol":[e],
                 "fbs":[f],
                 "restecg":[g],
                 "thalach":[h],
                 "exang":[i],
                 "oldpeak":[j],
                 "slope":[k],
                 "ca":[l],
                 "thal":[m]})
df2

In [ ]:
y_prd=classifier.predict(df2)
y_prd

In [ ]:
a=int(input("age :"))
b=int(input("sex :"))
c=int(input("cp :"))
d=int(input("trestbps :"))
e=int(input("chol	:"))
f=int(input("fbs :"))
g=int(input("	restecg	:"))
h=int(input("thalach :"))
i=int(input("exang	 :"))
j=int(input("oldpeak :"))
k=int(input("slope	 :"))
l=int(input("ca	:"))
m=int(input("thal	:"))
df3=pd.DataFrame({"age":[a],
                 "sex":[b],
                 "cp":[c],
                 "trestbps":[d],
                 "chol":[e],
                 "fbs":[f],
                 "restecg":[g],
                 "thalach":[h],
                 "exang":[i],
                 "oldpeak":[j],
                 "slope":[k],
                 "ca":[l],
                 "thal":[m]})
df3

In [ ]:
1y_pred=classifier.predict(df3)
y_pred

In [ ]:

























1